webdriver {
  driver = chrome
  autodownload = true

  capabilities {
    browserName = "chrome"
    "goog:chromeOptions" {
      args = [
        "--start-maximized",
        "--remote-allow-origins=*",
        "--disable-dev-shm-usage",
        "--no-sandbox",
        "--disable-notifications",
        "--disable-popup-blocking"
      ]
    }
  }
}

webdriver.base.url = "https://logistica-frontend-04lk.onrender.com"

serenity {
  project.name = "Automatización E2E Sistema de Tracking Logístico"
  take.screenshots = FOR_FAILURES
  reports.show.step.details = true
  logging = VERBOSE
}
