sonar.projectKey=jamartinezv2023_automatizaFE2026
sonar.organization=jamartinezv2023
sonar.host.url=https://sonarcloud.io
sonar.projectName=automatizaFE2026
sonar.sourceEncoding=UTF-8
sonar.java.source=17

sonar.sources=src/test/java
sonar.tests=src/test/resources

sonar.java.binaries=build/classes/java/test
sonar.junit.reportPaths=build/test-results/test

# Proyecto E2E: la cobertura unitaria no aplica a esta suite Serenity.
# La calidad se mide por escenarios E2E, estabilidad, trazabilidad y ejecución en CI.
sonar.coverage.exclusions=**/*
